# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 57f837a40af056e0084ef48ef54398f2041d7834a800b0c19f8c7947854e7d44847ee8930fc4e9e66f83e2e4d1ef007143ac97749d904acb7069f48f28a2307e

test:
  secret_key_base: c9f0e08a520094533e8a320a7536b03d4cd31be2169959f7682cd30945e5a30d3bdfbf52c306f0432fe34c33a3fd9d4e409cdcfd2555e014e57b153cae1a8b68

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
